version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=533939626955.dkr.ecr.ap-southeast-1.amazonaws.com/katalis-erp-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - n $NODE_10_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - find ./ -type f -name "nuxt.config*" -exec sed -i 's|http://192.168.1.102/|https://api.katalis.info/|g' {} \;
      - find ./ -type f -name "*Dockerfile*" -exec sed -i 's|abdarafi/secure-nginx:0.1|533939626955.dkr.ecr.ap-southeast-1.amazonaws.com/secure-nginx:0.1|g' {} \; 
      - yarn install
      - npm run build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"katalis-erp-frontend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
